//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExhibitGrid.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        public int AttributeId { get; set; }
        public string GridCode { get; set; }
        public string RowCode { get; set; }
        public string ColCode { get; set; }
        public string Attrib { get; set; }
        public string Value { get; set; }
        public string Expand { get; set; }
    }
}
