//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExhibitGrid.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeDeNorm
    {
        public int AttributeId { get; set; }
        public string GridCode { get; set; }
        public string RowCode { get; set; }
        public string ColCode { get; set; }
        public string RowAttrib1 { get; set; }
        public string RowAttrib2 { get; set; }
        public string RowAttrib3 { get; set; }
        public string RowAttrib4 { get; set; }
        public string RowAttrib5 { get; set; }
        public string RowAttrib6 { get; set; }
        public Nullable<bool> RowAttrib7 { get; set; }
        public Nullable<bool> RowAttrib8 { get; set; }
        public Nullable<bool> RowAttrib9 { get; set; }
        public Nullable<bool> RowAttrib10 { get; set; }
        public Nullable<bool> RowAttrib11 { get; set; }
        public Nullable<bool> RowAttrib12 { get; set; }
        public string CellAttrib1 { get; set; }
        public string CellAttrib2 { get; set; }
        public string CellAttrib3 { get; set; }
        public string CellAttrib4 { get; set; }
        public string CellAttrib5 { get; set; }
        public string CellAttrib6 { get; set; }
        public Nullable<bool> CellAttrib7 { get; set; }
        public Nullable<bool> CellAttrib8 { get; set; }
        public Nullable<bool> CellAttrib9 { get; set; }
        public Nullable<bool> CellAttrib10 { get; set; }
        public Nullable<bool> CellAttrib11 { get; set; }
        public Nullable<bool> CellAttrib12 { get; set; }
    }
}
