//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExhibitGrid.EntityDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ExhibitProtoEntities : DbContext
    {
        public ExhibitProtoEntities()
            : base("name=ExhibitProtoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CalcExpression> CalcExpressions { get; set; }
        public virtual DbSet<CalcOperand> CalcOperands { get; set; }
        public virtual DbSet<Expression> Expressions { get; set; }
        public virtual DbSet<Operand> Operands { get; set; }
    
        public virtual ObjectResult<GetCalcs_Result> GetCalcs(string gridCode)
        {
            var gridCodeParameter = gridCode != null ?
                new ObjectParameter("GridCode", gridCode) :
                new ObjectParameter("GridCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCalcs_Result>("GetCalcs", gridCodeParameter);
        }
    }
}
