//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExhibitGrid.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operand
    {
        public string TargetGridCode { get; set; }
        public string TargetRowCode { get; set; }
        public string TargetColCode { get; set; }
        public string GridCode { get; set; }
        public string RowCode { get; set; }
        public string ColCode { get; set; }
    
        public virtual Expression Expression { get; set; }
    }
}
