//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExhibitGrid.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Widget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Widget()
        {
            this.WidgetSelectionWidgets = new HashSet<WidgetSelectionWidget>();
            this.WidgetContexts = new HashSet<WidgetContext>();
        }
    
        public int WidgetId { get; set; }
        public string Code { get; set; }
        public int WidgetTypeId { get; set; }
        public string Description { get; set; }
        public string DataSourceReadAction { get; set; }
        public string TextMask { get; set; }
        public string NumFormat { get; set; }
        public Nullable<int> Decimals { get; set; }
        public Nullable<int> MaxVal { get; set; }
        public Nullable<int> MinVal { get; set; }
    
        public virtual WidgetType WidgetType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WidgetSelectionWidget> WidgetSelectionWidgets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WidgetContext> WidgetContexts { get; set; }
    }
}
